packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - 'vue'
  - '@vue/*'
  - unocss
  - '@unocss*'
  - '@types/node'
  - 'vitest'
  - '@vitest/*'
  - vue-router
  - '@quasar/*'
