import type Element from '../../nodes/element/Element.js';
import type CSSRule from '../CSSRule.js';
import * as PropertySymbol from '../../PropertySymbol.js';
import type BrowserWindow from '../../window/BrowserWindow.js';
/**
 * CSS Style Declaration.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration
 */
export default class CSSStyleDeclaration {
    #private;
    readonly parentRule: CSSRule | null;
    [PropertySymbol.window]: BrowserWindow;
    /**
     * Constructor.
     *
     * @param illegalConstructorSymbol Illegal constructor symbol.
     * @param window Window.
     * @param [options] Options.
     * @param [options.element] Element.
     * @param [options.computed] Computed.
     */
    constructor(illegalConstructorSymbol: symbol, window: BrowserWindow, options?: {
        element?: Element;
        computed?: boolean;
    });
    /**
     * Index properties
     */
    get 0(): string | undefined;
    get 1(): string | undefined;
    get 2(): string | undefined;
    get 3(): string | undefined;
    get 4(): string | undefined;
    get 5(): string | undefined;
    get 6(): string | undefined;
    get 7(): string | undefined;
    get 8(): string | undefined;
    get 9(): string | undefined;
    get 10(): string | undefined;
    get 11(): string | undefined;
    get 12(): string | undefined;
    get 13(): string | undefined;
    get 14(): string | undefined;
    get 15(): string | undefined;
    get 16(): string | undefined;
    get 17(): string | undefined;
    get 18(): string | undefined;
    get 19(): string | undefined;
    get 20(): string | undefined;
    get 21(): string | undefined;
    get 22(): string | undefined;
    get 23(): string | undefined;
    get 24(): string | undefined;
    get 25(): string | undefined;
    get 26(): string | undefined;
    get 27(): string | undefined;
    get 28(): string | undefined;
    get 29(): string | undefined;
    get 30(): string | undefined;
    get 31(): string | undefined;
    get 32(): string | undefined;
    get 33(): string | undefined;
    get 34(): string | undefined;
    get 35(): string | undefined;
    get 36(): string | undefined;
    get 37(): string | undefined;
    get 38(): string | undefined;
    get 39(): string | undefined;
    get 40(): string | undefined;
    get 41(): string | undefined;
    get 42(): string | undefined;
    get 43(): string | undefined;
    get 44(): string | undefined;
    get 45(): string | undefined;
    get 46(): string | undefined;
    get 47(): string | undefined;
    get 48(): string | undefined;
    get 49(): string | undefined;
    get 50(): string | undefined;
    get 51(): string | undefined;
    get 52(): string | undefined;
    get 53(): string | undefined;
    get 54(): string | undefined;
    get 55(): string | undefined;
    get 56(): string | undefined;
    get 57(): string | undefined;
    get 58(): string | undefined;
    get 59(): string | undefined;
    get 60(): string | undefined;
    get 61(): string | undefined;
    get 62(): string | undefined;
    get 63(): string | undefined;
    get 64(): string | undefined;
    get 65(): string | undefined;
    get 66(): string | undefined;
    get 67(): string | undefined;
    get 68(): string | undefined;
    get 69(): string | undefined;
    get 70(): string | undefined;
    get 71(): string | undefined;
    get 72(): string | undefined;
    get 73(): string | undefined;
    get 74(): string | undefined;
    get 75(): string | undefined;
    get 76(): string | undefined;
    get 77(): string | undefined;
    get 78(): string | undefined;
    get 79(): string | undefined;
    get 80(): string | undefined;
    get 81(): string | undefined;
    get 82(): string | undefined;
    get 83(): string | undefined;
    get 84(): string | undefined;
    get 85(): string | undefined;
    get 86(): string | undefined;
    get 87(): string | undefined;
    get 88(): string | undefined;
    get 89(): string | undefined;
    get 90(): string | undefined;
    get 91(): string | undefined;
    get 92(): string | undefined;
    get 93(): string | undefined;
    get 94(): string | undefined;
    get 95(): string | undefined;
    get 96(): string | undefined;
    get 97(): string | undefined;
    get 98(): string | undefined;
    get 99(): string | undefined;
    get 100(): string | undefined;
    get 101(): string | undefined;
    get 102(): string | undefined;
    get 103(): string | undefined;
    get 104(): string | undefined;
    get 105(): string | undefined;
    get 106(): string | undefined;
    get 107(): string | undefined;
    get 108(): string | undefined;
    get 109(): string | undefined;
    get 110(): string | undefined;
    get 111(): string | undefined;
    get 112(): string | undefined;
    get 113(): string | undefined;
    get 114(): string | undefined;
    get 115(): string | undefined;
    get 116(): string | undefined;
    get 117(): string | undefined;
    get 118(): string | undefined;
    get 119(): string | undefined;
    get 120(): string | undefined;
    get 121(): string | undefined;
    get 122(): string | undefined;
    get 123(): string | undefined;
    get 124(): string | undefined;
    get 125(): string | undefined;
    get 126(): string | undefined;
    get 127(): string | undefined;
    get 128(): string | undefined;
    get 129(): string | undefined;
    get 130(): string | undefined;
    get 131(): string | undefined;
    get 132(): string | undefined;
    get 133(): string | undefined;
    get 134(): string | undefined;
    get 135(): string | undefined;
    get 136(): string | undefined;
    get 137(): string | undefined;
    get 138(): string | undefined;
    get 139(): string | undefined;
    get 140(): string | undefined;
    get 141(): string | undefined;
    get 142(): string | undefined;
    get 143(): string | undefined;
    get 144(): string | undefined;
    get 145(): string | undefined;
    get 146(): string | undefined;
    get 147(): string | undefined;
    get 148(): string | undefined;
    get 149(): string | undefined;
    get 150(): string | undefined;
    get 151(): string | undefined;
    get 152(): string | undefined;
    get 153(): string | undefined;
    get 154(): string | undefined;
    get 155(): string | undefined;
    get 156(): string | undefined;
    get 157(): string | undefined;
    get 158(): string | undefined;
    get 159(): string | undefined;
    get 160(): string | undefined;
    get 161(): string | undefined;
    get 162(): string | undefined;
    get 163(): string | undefined;
    get 164(): string | undefined;
    get 165(): string | undefined;
    get 166(): string | undefined;
    get 167(): string | undefined;
    get 168(): string | undefined;
    get 169(): string | undefined;
    get 170(): string | undefined;
    get 171(): string | undefined;
    get 172(): string | undefined;
    get 173(): string | undefined;
    get 174(): string | undefined;
    get 175(): string | undefined;
    get 176(): string | undefined;
    get 177(): string | undefined;
    get 178(): string | undefined;
    get 179(): string | undefined;
    get 180(): string | undefined;
    get 181(): string | undefined;
    get 182(): string | undefined;
    get 183(): string | undefined;
    get 184(): string | undefined;
    get 185(): string | undefined;
    get 186(): string | undefined;
    get 187(): string | undefined;
    get 188(): string | undefined;
    get 189(): string | undefined;
    get 190(): string | undefined;
    get 191(): string | undefined;
    get 192(): string | undefined;
    get 193(): string | undefined;
    get 194(): string | undefined;
    get 195(): string | undefined;
    get 196(): string | undefined;
    get 197(): string | undefined;
    get 198(): string | undefined;
    get 199(): string | undefined;
    get 200(): string | undefined;
    get 201(): string | undefined;
    get 202(): string | undefined;
    get 203(): string | undefined;
    get 204(): string | undefined;
    get 205(): string | undefined;
    get 206(): string | undefined;
    get 207(): string | undefined;
    get 208(): string | undefined;
    get 209(): string | undefined;
    get 210(): string | undefined;
    get 211(): string | undefined;
    get 212(): string | undefined;
    get 213(): string | undefined;
    get 214(): string | undefined;
    get 215(): string | undefined;
    get 216(): string | undefined;
    get 217(): string | undefined;
    get 218(): string | undefined;
    get 219(): string | undefined;
    get 220(): string | undefined;
    get 221(): string | undefined;
    get 222(): string | undefined;
    get 223(): string | undefined;
    get 224(): string | undefined;
    get 225(): string | undefined;
    get 226(): string | undefined;
    get 227(): string | undefined;
    get 228(): string | undefined;
    get 229(): string | undefined;
    get 230(): string | undefined;
    get 231(): string | undefined;
    get 232(): string | undefined;
    get 233(): string | undefined;
    get 234(): string | undefined;
    get 235(): string | undefined;
    get 236(): string | undefined;
    get 237(): string | undefined;
    get 238(): string | undefined;
    get 239(): string | undefined;
    get 240(): string | undefined;
    get 241(): string | undefined;
    get 242(): string | undefined;
    get 243(): string | undefined;
    get 244(): string | undefined;
    get 245(): string | undefined;
    get 246(): string | undefined;
    get 247(): string | undefined;
    get 248(): string | undefined;
    get 249(): string | undefined;
    get 250(): string | undefined;
    get 251(): string | undefined;
    get 252(): string | undefined;
    get 253(): string | undefined;
    get 254(): string | undefined;
    get 255(): string | undefined;
    get 256(): string | undefined;
    get 257(): string | undefined;
    get 258(): string | undefined;
    get 259(): string | undefined;
    get 260(): string | undefined;
    get 261(): string | undefined;
    get 262(): string | undefined;
    get 263(): string | undefined;
    get 264(): string | undefined;
    get 265(): string | undefined;
    get 266(): string | undefined;
    get 267(): string | undefined;
    get 268(): string | undefined;
    get 269(): string | undefined;
    get 270(): string | undefined;
    get 271(): string | undefined;
    get 272(): string | undefined;
    get 273(): string | undefined;
    get 274(): string | undefined;
    get 275(): string | undefined;
    get 276(): string | undefined;
    get 277(): string | undefined;
    get 278(): string | undefined;
    get 279(): string | undefined;
    get 280(): string | undefined;
    get 281(): string | undefined;
    get 282(): string | undefined;
    get 283(): string | undefined;
    get 284(): string | undefined;
    get 285(): string | undefined;
    get 286(): string | undefined;
    get 287(): string | undefined;
    get 288(): string | undefined;
    get 289(): string | undefined;
    get 290(): string | undefined;
    get 291(): string | undefined;
    get 292(): string | undefined;
    get 293(): string | undefined;
    get 294(): string | undefined;
    get 295(): string | undefined;
    get 296(): string | undefined;
    get 297(): string | undefined;
    get 298(): string | undefined;
    get 299(): string | undefined;
    get 300(): string | undefined;
    get 301(): string | undefined;
    get 302(): string | undefined;
    get 303(): string | undefined;
    get 304(): string | undefined;
    get 305(): string | undefined;
    get 306(): string | undefined;
    get 307(): string | undefined;
    get 308(): string | undefined;
    get 309(): string | undefined;
    get 310(): string | undefined;
    get 311(): string | undefined;
    get 312(): string | undefined;
    get 313(): string | undefined;
    get 314(): string | undefined;
    get 315(): string | undefined;
    get 316(): string | undefined;
    get 317(): string | undefined;
    get 318(): string | undefined;
    get 319(): string | undefined;
    get 320(): string | undefined;
    get 321(): string | undefined;
    get 322(): string | undefined;
    get 323(): string | undefined;
    get 324(): string | undefined;
    get 325(): string | undefined;
    get 326(): string | undefined;
    get 327(): string | undefined;
    get 328(): string | undefined;
    get 329(): string | undefined;
    get 330(): string | undefined;
    get 331(): string | undefined;
    get 332(): string | undefined;
    get 333(): string | undefined;
    get 334(): string | undefined;
    get 335(): string | undefined;
    get 336(): string | undefined;
    get 337(): string | undefined;
    get 338(): string | undefined;
    get 339(): string | undefined;
    get 340(): string | undefined;
    get 341(): string | undefined;
    get 342(): string | undefined;
    get 343(): string | undefined;
    get 344(): string | undefined;
    get 345(): string | undefined;
    get 346(): string | undefined;
    get 347(): string | undefined;
    get 348(): string | undefined;
    get 349(): string | undefined;
    get 350(): string | undefined;
    get 351(): string | undefined;
    get 352(): string | undefined;
    get 353(): string | undefined;
    get 354(): string | undefined;
    get 355(): string | undefined;
    get 356(): string | undefined;
    get 357(): string | undefined;
    get 358(): string | undefined;
    get 359(): string | undefined;
    get 360(): string | undefined;
    get 361(): string | undefined;
    get 362(): string | undefined;
    get 363(): string | undefined;
    get 364(): string | undefined;
    get 365(): string | undefined;
    get 366(): string | undefined;
    get 367(): string | undefined;
    get 368(): string | undefined;
    get 369(): string | undefined;
    get 370(): string | undefined;
    get 371(): string | undefined;
    get 372(): string | undefined;
    get 373(): string | undefined;
    get 374(): string | undefined;
    get 375(): string | undefined;
    get 376(): string | undefined;
    get 377(): string | undefined;
    get 378(): string | undefined;
    get 379(): string | undefined;
    get 380(): string | undefined;
    get 381(): string | undefined;
    get 382(): string | undefined;
    get 383(): string | undefined;
    get 384(): string | undefined;
    get 385(): string | undefined;
    get 386(): string | undefined;
    get 387(): string | undefined;
    get 388(): string | undefined;
    get 389(): string | undefined;
    get 390(): string | undefined;
    get 391(): string | undefined;
    get 392(): string | undefined;
    get 393(): string | undefined;
    /**
     * CSS properties
     */
    get accentColor(): string;
    set accentColor(value: string);
    get appRegion(): string;
    set appRegion(value: string);
    get alignContent(): string;
    set alignContent(value: string);
    get alignItems(): string;
    set alignItems(value: string);
    get alignSelf(): string;
    set alignSelf(value: string);
    get alignmentBaseline(): string;
    set alignmentBaseline(value: string);
    get all(): string;
    set all(value: string);
    get animation(): string;
    set animation(value: string);
    get animationDelay(): string;
    set animationDelay(value: string);
    get animationDirection(): string;
    set animationDirection(value: string);
    get animationDuration(): string;
    set animationDuration(value: string);
    get animationFillMode(): string;
    set animationFillMode(value: string);
    get animationIterationCount(): string;
    set animationIterationCount(value: string);
    get animationName(): string;
    set animationName(value: string);
    get animationPlayState(): string;
    set animationPlayState(value: string);
    get animationTimingFunction(): string;
    set animationTimingFunction(value: string);
    get appearance(): string;
    set appearance(value: string);
    get backdropFilter(): string;
    set backdropFilter(value: string);
    get backfaceVisibility(): string;
    set backfaceVisibility(value: string);
    get background(): string;
    set background(value: string);
    get backgroundAttachment(): string;
    set backgroundAttachment(value: string);
    get backgroundBlendMode(): string;
    set backgroundBlendMode(value: string);
    get backgroundClip(): string;
    set backgroundClip(value: string);
    get backgroundColor(): string;
    set backgroundColor(value: string);
    get backgroundImage(): string;
    set backgroundImage(value: string);
    get backgroundOrigin(): string;
    set backgroundOrigin(value: string);
    get backgroundPosition(): string;
    set backgroundPosition(value: string);
    get backgroundPositionX(): string;
    set backgroundPositionX(value: string);
    get backgroundPositionY(): string;
    set backgroundPositionY(value: string);
    get backgroundRepeat(): string;
    set backgroundRepeat(value: string);
    get backgroundRepeatX(): string;
    set backgroundRepeatX(value: string);
    get backgroundRepeatY(): string;
    set backgroundRepeatY(value: string);
    get backgroundSize(): string;
    set backgroundSize(value: string);
    get baselineShift(): string;
    set baselineShift(value: string);
    get blockSize(): string;
    set blockSize(value: string);
    get border(): string;
    set border(value: string);
    get borderBlockEnd(): string;
    set borderBlockEnd(value: string);
    get borderBlockEndColor(): string;
    set borderBlockEndColor(value: string);
    get borderBlockEndStyle(): string;
    set borderBlockEndStyle(value: string);
    get borderBlockEndWidth(): string;
    set borderBlockEndWidth(value: string);
    get borderBlockStart(): string;
    set borderBlockStart(value: string);
    get borderBlockStartColor(): string;
    set borderBlockStartColor(value: string);
    get borderBlockStartStyle(): string;
    set borderBlockStartStyle(value: string);
    get borderBlockStartWidth(): string;
    set borderBlockStartWidth(value: string);
    get borderBottom(): string;
    set borderBottom(value: string);
    get borderBottomColor(): string;
    set borderBottomColor(value: string);
    get borderBottomLeftRadius(): string;
    set borderBottomLeftRadius(value: string);
    get borderBottomRightRadius(): string;
    set borderBottomRightRadius(value: string);
    get borderBottomStyle(): string;
    set borderBottomStyle(value: string);
    get borderBottomWidth(): string;
    set borderBottomWidth(value: string);
    get borderCollapse(): string;
    set borderCollapse(value: string);
    get borderColor(): string;
    set borderColor(value: string);
    get borderImage(): string;
    set borderImage(value: string);
    get borderImageOutset(): string;
    set borderImageOutset(value: string);
    get borderImageRepeat(): string;
    set borderImageRepeat(value: string);
    get borderImageSlice(): string;
    set borderImageSlice(value: string);
    get borderImageSource(): string;
    set borderImageSource(value: string);
    get borderImageWidth(): string;
    set borderImageWidth(value: string);
    get borderInlineEnd(): string;
    set borderInlineEnd(value: string);
    get borderInlineEndColor(): string;
    set borderInlineEndColor(value: string);
    get borderInlineEndStyle(): string;
    set borderInlineEndStyle(value: string);
    get borderInlineEndWidth(): string;
    set borderInlineEndWidth(value: string);
    get borderInlineStart(): string;
    set borderInlineStart(value: string);
    get borderInlineStartColor(): string;
    set borderInlineStartColor(value: string);
    get borderInlineStartStyle(): string;
    set borderInlineStartStyle(value: string);
    get borderInlineStartWidth(): string;
    set borderInlineStartWidth(value: string);
    get borderLeft(): string;
    set borderLeft(value: string);
    get borderLeftColor(): string;
    set borderLeftColor(value: string);
    get borderLeftStyle(): string;
    set borderLeftStyle(value: string);
    get borderLeftWidth(): string;
    set borderLeftWidth(value: string);
    get borderRadius(): string;
    set borderRadius(value: string);
    get borderRight(): string;
    set borderRight(value: string);
    get borderRightColor(): string;
    set borderRightColor(value: string);
    get borderRightStyle(): string;
    set borderRightStyle(value: string);
    get borderRightWidth(): string;
    set borderRightWidth(value: string);
    get borderSpacing(): string;
    set borderSpacing(value: string);
    get borderStyle(): string;
    set borderStyle(value: string);
    get borderTop(): string;
    set borderTop(value: string);
    get borderTopColor(): string;
    set borderTopColor(value: string);
    get borderTopLeftRadius(): string;
    set borderTopLeftRadius(value: string);
    get borderTopRightRadius(): string;
    set borderTopRightRadius(value: string);
    get borderTopStyle(): string;
    set borderTopStyle(value: string);
    get borderTopWidth(): string;
    set borderTopWidth(value: string);
    get borderWidth(): string;
    set borderWidth(value: string);
    get borderEndEndRadius(): string;
    set borderEndEndRadius(value: string);
    get borderEndStartRadius(): string;
    set borderEndStartRadius(value: string);
    get borderStartEndRadius(): string;
    set borderStartEndRadius(value: string);
    get borderStartStartRadius(): string;
    set borderStartStartRadius(value: string);
    get bottom(): string;
    set bottom(value: string);
    get boxShadow(): string;
    set boxShadow(value: string);
    get boxSizing(): string;
    set boxSizing(value: string);
    get breakAfter(): string;
    set breakAfter(value: string);
    get breakBefore(): string;
    set breakBefore(value: string);
    get breakInside(): string;
    set breakInside(value: string);
    get bufferedRendering(): string;
    set bufferedRendering(value: string);
    get captionSide(): string;
    set captionSide(value: string);
    get caretColor(): string;
    set caretColor(value: string);
    get clear(): string;
    set clear(value: string);
    get clip(): string;
    set clip(value: string);
    get clipPath(): string;
    set clipPath(value: string);
    get clipRule(): string;
    set clipRule(value: string);
    get color(): string;
    set color(value: string);
    get colorInterpolation(): string;
    set colorInterpolation(value: string);
    get colorInterpolationFilters(): string;
    set colorInterpolationFilters(value: string);
    get colorRendering(): string;
    set colorRendering(value: string);
    get colorScheme(): string;
    set colorScheme(value: string);
    get columnCount(): string;
    set columnCount(value: string);
    get columnFill(): string;
    set columnFill(value: string);
    get columnGap(): string;
    set columnGap(value: string);
    get columnRule(): string;
    set columnRule(value: string);
    get columnRuleColor(): string;
    set columnRuleColor(value: string);
    get columnRuleStyle(): string;
    set columnRuleStyle(value: string);
    get columnRuleWidth(): string;
    set columnRuleWidth(value: string);
    get columnSpan(): string;
    set columnSpan(value: string);
    get columnWidth(): string;
    set columnWidth(value: string);
    get columns(): string;
    set columns(value: string);
    get contain(): string;
    set contain(value: string);
    get containIntrinsicSize(): string;
    set containIntrinsicSize(value: string);
    get content(): string;
    set content(value: string);
    get contentVisibility(): string;
    set contentVisibility(value: string);
    get counterIncrement(): string;
    set counterIncrement(value: string);
    get counterReset(): string;
    set counterReset(value: string);
    get counterSet(): string;
    set counterSet(value: string);
    get containIntrinsicBlockSize(): string;
    set containIntrinsicBlockSize(value: string);
    get containIntrinsicHeight(): string;
    set containIntrinsicHeight(value: string);
    get containIntrinsicInlineSize(): string;
    set containIntrinsicInlineSize(value: string);
    get containIntrinsicWidth(): string;
    set containIntrinsicWidth(value: string);
    get cssFloat(): string;
    set cssFloat(value: string);
    get cursor(): string;
    set cursor(value: string);
    get cx(): string;
    set cx(value: string);
    get cy(): string;
    set cy(value: string);
    get d(): string;
    set d(value: string);
    get direction(): string;
    set direction(value: string);
    get display(): string;
    set display(value: string);
    get dominantBaseline(): string;
    set dominantBaseline(value: string);
    get emptyCells(): string;
    set emptyCells(value: string);
    get fill(): string;
    set fill(value: string);
    get fillOpacity(): string;
    set fillOpacity(value: string);
    get fillRule(): string;
    set fillRule(value: string);
    get filter(): string;
    set filter(value: string);
    get flex(): string;
    set flex(value: string);
    get flexBasis(): string;
    set flexBasis(value: string);
    get flexDirection(): string;
    set flexDirection(value: string);
    get flexFlow(): string;
    set flexFlow(value: string);
    get flexGrow(): string;
    set flexGrow(value: string);
    get flexShrink(): string;
    set flexShrink(value: string);
    get flexWrap(): string;
    set flexWrap(value: string);
    get float(): string;
    set float(value: string);
    get floodColor(): string;
    set floodColor(value: string);
    get floodOpacity(): string;
    set floodOpacity(value: string);
    get font(): string;
    set font(value: string);
    get fontDisplay(): string;
    set fontDisplay(value: string);
    get fontFamily(): string;
    set fontFamily(value: string);
    get fontFeatureSettings(): string;
    set fontFeatureSettings(value: string);
    get fontKerning(): string;
    set fontKerning(value: string);
    get fontOpticalSizing(): string;
    set fontOpticalSizing(value: string);
    get fontSize(): string;
    set fontSize(value: string);
    get fontStretch(): string;
    set fontStretch(value: string);
    get fontStyle(): string;
    set fontStyle(value: string);
    get fontVariant(): string;
    set fontVariant(value: string);
    get fontVariantCaps(): string;
    set fontVariantCaps(value: string);
    get fontVariantEastAsian(): string;
    set fontVariantEastAsian(value: string);
    get fontVariantLigatures(): string;
    set fontVariantLigatures(value: string);
    get fontVariantNumeric(): string;
    set fontVariantNumeric(value: string);
    get fontVariationSettings(): string;
    set fontVariationSettings(value: string);
    get fontPalette(): string;
    set fontPalette(value: string);
    get fontSynthesisSmallCaps(): string;
    set fontSynthesisSmallCaps(value: string);
    get fontSynthesisStyle(): string;
    set fontSynthesisStyle(value: string);
    get fontSynthesisWeight(): string;
    set fontSynthesisWeight(value: string);
    get fontWeight(): string;
    set fontWeight(value: string);
    get gap(): string;
    set gap(value: string);
    get grid(): string;
    set grid(value: string);
    get gridArea(): string;
    set gridArea(value: string);
    get gridAutoColumns(): string;
    set gridAutoColumns(value: string);
    get gridAutoFlow(): string;
    set gridAutoFlow(value: string);
    get gridAutoRows(): string;
    set gridAutoRows(value: string);
    get gridColumn(): string;
    set gridColumn(value: string);
    get gridColumnEnd(): string;
    set gridColumnEnd(value: string);
    get gridColumnGap(): string;
    set gridColumnGap(value: string);
    get gridColumnStart(): string;
    set gridColumnStart(value: string);
    get gridGap(): string;
    set gridGap(value: string);
    get gridRow(): string;
    set gridRow(value: string);
    get gridRowEnd(): string;
    set gridRowEnd(value: string);
    get gridRowGap(): string;
    set gridRowGap(value: string);
    get gridRowStart(): string;
    set gridRowStart(value: string);
    get gridTemplate(): string;
    set gridTemplate(value: string);
    get gridTemplateAreas(): string;
    set gridTemplateAreas(value: string);
    get gridTemplateColumns(): string;
    set gridTemplateColumns(value: string);
    get gridTemplateRows(): string;
    set gridTemplateRows(value: string);
    get height(): string;
    set height(value: string);
    get hyphens(): string;
    set hyphens(value: string);
    get imageOrientation(): string;
    set imageOrientation(value: string);
    get imageRendering(): string;
    set imageRendering(value: string);
    get inherits(): string;
    set inherits(value: string);
    get initialValue(): string;
    set initialValue(value: string);
    get inlineSize(): string;
    set inlineSize(value: string);
    get isolation(): string;
    set isolation(value: string);
    get insetBlockEnd(): string;
    set insetBlockEnd(value: string);
    get insetBlockStart(): string;
    set insetBlockStart(value: string);
    get insetInlineEnd(): string;
    set insetInlineEnd(value: string);
    get insetInlineStart(): string;
    set insetInlineStart(value: string);
    get justifyContent(): string;
    set justifyContent(value: string);
    get justifyItems(): string;
    set justifyItems(value: string);
    get justifySelf(): string;
    set justifySelf(value: string);
    get left(): string;
    set left(value: string);
    get letterSpacing(): string;
    set letterSpacing(value: string);
    get lightingColor(): string;
    set lightingColor(value: string);
    get lineBreak(): string;
    set lineBreak(value: string);
    get lineHeight(): string;
    set lineHeight(value: string);
    get listStyle(): string;
    set listStyle(value: string);
    get listStyleImage(): string;
    set listStyleImage(value: string);
    get listStylePosition(): string;
    set listStylePosition(value: string);
    get listStyleType(): string;
    set listStyleType(value: string);
    get margin(): string;
    set margin(value: string);
    get marginBlockEnd(): string;
    set marginBlockEnd(value: string);
    get marginBlockStart(): string;
    set marginBlockStart(value: string);
    get marginBottom(): string;
    set marginBottom(value: string);
    get marginInlineEnd(): string;
    set marginInlineEnd(value: string);
    get marginInlineStart(): string;
    set marginInlineStart(value: string);
    get marginLeft(): string;
    set marginLeft(value: string);
    get marginRight(): string;
    set marginRight(value: string);
    get marginTop(): string;
    set marginTop(value: string);
    get marker(): string;
    set marker(value: string);
    get markerEnd(): string;
    set markerEnd(value: string);
    get markerMid(): string;
    set markerMid(value: string);
    get markerStart(): string;
    set markerStart(value: string);
    get mask(): string;
    set mask(value: string);
    get maskType(): string;
    set maskType(value: string);
    get maxBlockSize(): string;
    set maxBlockSize(value: string);
    get maxHeight(): string;
    set maxHeight(value: string);
    get maxInlineSize(): string;
    set maxInlineSize(value: string);
    get maxWidth(): string;
    set maxWidth(value: string);
    get maxZoom(): string;
    set maxZoom(value: string);
    get minBlockSize(): string;
    set minBlockSize(value: string);
    get minHeight(): string;
    set minHeight(value: string);
    get minInlineSize(): string;
    set minInlineSize(value: string);
    get minWidth(): string;
    set minWidth(value: string);
    get minZoom(): string;
    set minZoom(value: string);
    get mixBlendMode(): string;
    set mixBlendMode(value: string);
    get objectFit(): string;
    set objectFit(value: string);
    get objectPosition(): string;
    set objectPosition(value: string);
    get offset(): string;
    set offset(value: string);
    get offsetDistance(): string;
    set offsetDistance(value: string);
    get offsetPath(): string;
    set offsetPath(value: string);
    get offsetRotate(): string;
    set offsetRotate(value: string);
    get opacity(): string;
    set opacity(value: string);
    get order(): string;
    set order(value: string);
    get orientation(): string;
    set orientation(value: string);
    get orphans(): string;
    set orphans(value: string);
    get outline(): string;
    set outline(value: string);
    get outlineColor(): string;
    set outlineColor(value: string);
    get outlineOffset(): string;
    set outlineOffset(value: string);
    get outlineStyle(): string;
    set outlineStyle(value: string);
    get outlineWidth(): string;
    set outlineWidth(value: string);
    get overflow(): string;
    set overflow(value: string);
    get overflowAnchor(): string;
    set overflowAnchor(value: string);
    get overflowWrap(): string;
    set overflowWrap(value: string);
    get overflowX(): string;
    set overflowX(value: string);
    get overflowY(): string;
    set overflowY(value: string);
    get overscrollBehavior(): string;
    set overscrollBehavior(value: string);
    get overscrollBehaviorBlock(): string;
    set overscrollBehaviorBlock(value: string);
    get overscrollBehaviorInline(): string;
    set overscrollBehaviorInline(value: string);
    get overscrollBehaviorX(): string;
    set overscrollBehaviorX(value: string);
    get overscrollBehaviorY(): string;
    set overscrollBehaviorY(value: string);
    get overflowClipMargin(): string;
    set overflowClipMargin(value: string);
    get padding(): string;
    set padding(value: string);
    get paddingBlockEnd(): string;
    set paddingBlockEnd(value: string);
    get paddingBlockStart(): string;
    set paddingBlockStart(value: string);
    get paddingBottom(): string;
    set paddingBottom(value: string);
    get paddingInlineEnd(): string;
    set paddingInlineEnd(value: string);
    get paddingInlineStart(): string;
    set paddingInlineStart(value: string);
    get paddingLeft(): string;
    set paddingLeft(value: string);
    get paddingRight(): string;
    set paddingRight(value: string);
    get paddingTop(): string;
    set paddingTop(value: string);
    get page(): string;
    set page(value: string);
    get pageBreakAfter(): string;
    set pageBreakAfter(value: string);
    get pageBreakBefore(): string;
    set pageBreakBefore(value: string);
    get pageBreakInside(): string;
    set pageBreakInside(value: string);
    get pageOrientation(): string;
    set pageOrientation(value: string);
    get paintOrder(): string;
    set paintOrder(value: string);
    get perspective(): string;
    set perspective(value: string);
    get perspectiveOrigin(): string;
    set perspectiveOrigin(value: string);
    get placeContent(): string;
    set placeContent(value: string);
    get placeItems(): string;
    set placeItems(value: string);
    get placeSelf(): string;
    set placeSelf(value: string);
    get pointerEvents(): string;
    set pointerEvents(value: string);
    get position(): string;
    set position(value: string);
    get quotes(): string;
    set quotes(value: string);
    get r(): string;
    set r(value: string);
    get resize(): string;
    set resize(value: string);
    get right(): string;
    set right(value: string);
    get rowGap(): string;
    set rowGap(value: string);
    get rubyPosition(): string;
    set rubyPosition(value: string);
    get rx(): string;
    set rx(value: string);
    get ry(): string;
    set ry(value: string);
    get scrollBehavior(): string;
    set scrollBehavior(value: string);
    get scrollMargin(): string;
    set scrollMargin(value: string);
    get scrollMarginBlock(): string;
    set scrollMarginBlock(value: string);
    get scrollMarginBlockEnd(): string;
    set scrollMarginBlockEnd(value: string);
    get scrollMarginBlockStart(): string;
    set scrollMarginBlockStart(value: string);
    get scrollMarginBottom(): string;
    set scrollMarginBottom(value: string);
    get scrollMarginInline(): string;
    set scrollMarginInline(value: string);
    get scrollMarginInlineEnd(): string;
    set scrollMarginInlineEnd(value: string);
    get scrollMarginInlineStart(): string;
    set scrollMarginInlineStart(value: string);
    get scrollMarginLeft(): string;
    set scrollMarginLeft(value: string);
    get scrollMarginRight(): string;
    set scrollMarginRight(value: string);
    get scrollMarginTop(): string;
    set scrollMarginTop(value: string);
    get scrollPadding(): string;
    set scrollPadding(value: string);
    get scrollPaddingBlock(): string;
    set scrollPaddingBlock(value: string);
    get scrollPaddingBlockEnd(): string;
    set scrollPaddingBlockEnd(value: string);
    get scrollPaddingBlockStart(): string;
    set scrollPaddingBlockStart(value: string);
    get scrollPaddingBottom(): string;
    set scrollPaddingBottom(value: string);
    get scrollPaddingInline(): string;
    set scrollPaddingInline(value: string);
    get scrollPaddingInlineEnd(): string;
    set scrollPaddingInlineEnd(value: string);
    get scrollPaddingInlineStart(): string;
    set scrollPaddingInlineStart(value: string);
    get scrollPaddingLeft(): string;
    set scrollPaddingLeft(value: string);
    get scrollPaddingRight(): string;
    set scrollPaddingRight(value: string);
    get scrollPaddingTop(): string;
    set scrollPaddingTop(value: string);
    get scrollSnapAlign(): string;
    set scrollSnapAlign(value: string);
    get scrollSnapStop(): string;
    set scrollSnapStop(value: string);
    get scrollSnapType(): string;
    set scrollSnapType(value: string);
    get shapeImageThreshold(): string;
    set shapeImageThreshold(value: string);
    get shapeMargin(): string;
    set shapeMargin(value: string);
    get shapeOutside(): string;
    set shapeOutside(value: string);
    get shapeRendering(): string;
    set shapeRendering(value: string);
    get size(): string;
    set size(value: string);
    get speak(): string;
    set speak(value: string);
    get src(): string;
    set src(value: string);
    get stopColor(): string;
    set stopColor(value: string);
    get stopOpacity(): string;
    set stopOpacity(value: string);
    get stroke(): string;
    set stroke(value: string);
    get strokeDasharray(): string;
    set strokeDasharray(value: string);
    get strokeDashoffset(): string;
    set strokeDashoffset(value: string);
    get strokeLinecap(): string;
    set strokeLinecap(value: string);
    get strokeLinejoin(): string;
    set strokeLinejoin(value: string);
    get strokeMiterlimit(): string;
    set strokeMiterlimit(value: string);
    get strokeOpacity(): string;
    set strokeOpacity(value: string);
    get strokeWidth(): string;
    set strokeWidth(value: string);
    get syntax(): string;
    set syntax(value: string);
    get scrollbarGutter(): string;
    set scrollbarGutter(value: string);
    get tabSize(): string;
    set tabSize(value: string);
    get tableLayout(): string;
    set tableLayout(value: string);
    get textAlign(): string;
    set textAlign(value: string);
    get textAlignLast(): string;
    set textAlignLast(value: string);
    get textAnchor(): string;
    set textAnchor(value: string);
    get textCombineUpright(): string;
    set textCombineUpright(value: string);
    get textDecoration(): string;
    set textDecoration(value: string);
    get textDecorationColor(): string;
    set textDecorationColor(value: string);
    get textDecorationLine(): string;
    set textDecorationLine(value: string);
    get textDecorationSkipInk(): string;
    set textDecorationSkipInk(value: string);
    get textDecorationStyle(): string;
    set textDecorationStyle(value: string);
    get textIndent(): string;
    set textIndent(value: string);
    get textOrientation(): string;
    set textOrientation(value: string);
    get textOverflow(): string;
    set textOverflow(value: string);
    get textRendering(): string;
    set textRendering(value: string);
    get textShadow(): string;
    set textShadow(value: string);
    get textSizeAdjust(): string;
    set textSizeAdjust(value: string);
    get textTransform(): string;
    set textTransform(value: string);
    get textUnderlinePosition(): string;
    set textUnderlinePosition(value: string);
    get top(): string;
    set top(value: string);
    get touchAction(): string;
    set touchAction(value: string);
    get transform(): string;
    set transform(value: string);
    get transformBox(): string;
    set transformBox(value: string);
    get transformOrigin(): string;
    set transformOrigin(value: string);
    get transformStyle(): string;
    set transformStyle(value: string);
    get transition(): string;
    set transition(value: string);
    get transitionDelay(): string;
    set transitionDelay(value: string);
    get transitionDuration(): string;
    set transitionDuration(value: string);
    get transitionProperty(): string;
    set transitionProperty(value: string);
    get transitionTimingFunction(): string;
    set transitionTimingFunction(value: string);
    get textEmphasisColor(): string;
    set textEmphasisColor(value: string);
    get textEmphasisPosition(): string;
    set textEmphasisPosition(value: string);
    get textEmphasisStyle(): string;
    set textEmphasisStyle(value: string);
    get unicodeBidi(): string;
    set unicodeBidi(value: string);
    get unicodeRange(): string;
    set unicodeRange(value: string);
    get userSelect(): string;
    set userSelect(value: string);
    get userZoom(): string;
    set userZoom(value: string);
    get vectorEffect(): string;
    set vectorEffect(value: string);
    get verticalAlign(): string;
    set verticalAlign(value: string);
    get visibility(): string;
    set visibility(value: string);
    get whiteSpace(): string;
    set whiteSpace(value: string);
    get widows(): string;
    set widows(value: string);
    get width(): string;
    set width(value: string);
    get willChange(): string;
    set willChange(value: string);
    get wordBreak(): string;
    set wordBreak(value: string);
    get wordSpacing(): string;
    set wordSpacing(value: string);
    get wordWrap(): string;
    set wordWrap(value: string);
    get writingMode(): string;
    set writingMode(value: string);
    get x(): string;
    set x(value: string);
    get y(): string;
    set y(value: string);
    get zIndex(): string;
    set zIndex(value: string);
    get zoom(): string;
    set zoom(value: string);
    get containerType(): string;
    set containerType(value: string);
    get containerName(): string;
    set containerName(value: string);
    get aspectRatio(): string;
    set aspectRatio(value: string);
    /**
     * Returns length.
     *
     * @returns Length.
     */
    get length(): number;
    /**
     * Returns the style decleration as a CSS text.
     *
     * @returns CSS text.
     */
    get cssText(): string;
    /**
     * Sets CSS text.
     *
     * @param cssText CSS text.
     */
    set cssText(cssText: string);
    /**
     * Returns item.
     *
     * @param index Index.
     * @returns Item.
     */
    item(index: number): string;
    /**
     * Set a property.
     *
     * @param name Property name.
     * @param value Value. Must not contain "!important" as that should be set using the priority parameter.
     * @param [priority] Can be "important", or an empty string.
     */
    setProperty(name: string, value: string, priority?: 'important' | '' | undefined): void;
    /**
     * Removes a property.
     *
     * @param name Property name in kebab case.
     * @param value Value. Must not contain "!important" as that should be set using the priority parameter.
     * @param [priority] Can be "important", or an empty string.
     */
    removeProperty(name: string): void;
    /**
     * Returns a property.
     *
     * @param name Property name in kebab case.
     * @returns Property value.
     */
    getPropertyValue(name: string): string;
    /**
     * Returns a property.
     *
     * @param name Property name in kebab case.
     * @returns "important" if set to be important.
     */
    getPropertyPriority(name: string): string;
}
//# sourceMappingURL=CSSStyleDeclaration.d.ts.map